# config.yaml
env:
    env_id: 'EpMineEnv-v0' # 环境名
    env_num: 4  # 环境数
    exp_name: 'RobotCv'
    reward_scaling: False
    max_episode_steps: 1000
    only_image: True
    only_state: False

train:
    algo: ppo   # [sac, ppo, ddpg]
    n_timesteps: 1000000
    batch_size: 256
    gamma: 0.99
    learning_rate: 0.0003
    device: 'cuda'
    seed: 0
    use_sde: False
    ent_coef: 0.1