# config.yaml
env:
    env_id: 'EpMineEnv-v0' # 环境名
    env_num: 4  # 环境数
    exp_name: 'RobotCv' # 实验名
    reward_scaling: False # 奖励缩放
    max_episode_steps: 1000 
    only_image: True 
    only_state: False
    dist_reward: 'v0' # 采用何种奖励函数
    no_graph: False


train:
    algo: ppo   # [sac, ppo, ddpg]
    policy: CnnPolicy # [CnnPolicy, CnnLstmPolicy]
    n_timesteps: 1000000
    batch_size: 256
    gamma: 0.99
    learning_rate: 0.0003
    device: 'cuda'
    seed: 0
    use_sde: False
    ent_coef: 0.0
    target_kl: 100000  # 该参数取极大值时无效